apiVersion: v1
kind: Config
clusters:
  - name: simple-authz-service
    cluster:
      server: http://172.30.31.208:8888/authorize      
users:
  - name: authz-service
    user:
      token: test-token
current-context: webhook
contexts:
- context:
    cluster: simple-authz-service
    user: authz-service
  name: webhook